#FROM jupyter/base-notebook:lab-3.1.18
FROM python:3.8

MAINTAINER Barbara Hill <bhill@broadinstitute.org>

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /MBTA_Project/
COPY MBTA_Project.ipynb /MBTA_Project/


# to build
# docker build --rm -t mbta-project:0.1 .
# to run docker run --rm -it mbta-project:0.1
# see README.md for further documentation